version: '2'

services:
  edesia: #name of your service
    build:
        context: .
        dockerfile: ./DockerFileNode
    image: edesia/api:0.1
    ports:
      - "80:3000"
    volumes:
      - ./app:/usr/src/app
    links:
      - database 
    depends_on:
      - database
      
  database: 
    image: mongo:3.2
