version: '2'

services:
  edesia: #name of your service
    build:
        context: .
        dockerfile: ./DockerFileNode
    image: edesia/api:0.1
    ports:
      - "80:3000"
    volumes:
      - ./app:/usr/src/app
    links: 
      - database2
    depends_on:
      - database2

  
  
  database2:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: edesia


